plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

RSpec/ExampleLength:
  Max: 20
  Exclude:
    - 'spec/integration/**/*'

RSpec/MultipleExpectations:
  Max: 10
  Exclude:
    - 'spec/integration/**/*'

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

# Integration tests describe workflows, not classes
RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'

# Live integration tests need before(:all)/after(:all) for WebMock management
RSpec/BeforeAfterAll:
  Exclude:
    - 'spec/integration/**/*'
