require 'uri'

module Safire
  module Protocols
    # Validates and normalizes caller-controlled UDAP Dynamic Client
    # Registration metadata before a software statement is signed.
    #
    # The object enforces the registration metadata rules from
    # [UDAP Security STU2](https://hl7.org/fhir/us/udap-security/STU2/registration.html).
    # It preserves JSON-compatible RFC 7591 extension metadata while preventing
    # callers from overriding JWT claims, request envelope fields, or fixed
    # UDAP values generated by Safire.
    #
    # @example Build authorization-code registration metadata
    #   metadata = Safire::Protocols::UdapRegistrationMetadata.new(
    #     {
    #       client_name: 'Example Health App',
    #       contacts: ['mailto:security@example.com'],
    #       grant_types: %w[authorization_code refresh_token],
    #       scope: 'openid system/Patient.rs',
    #       redirect_uris: ['https://app.example.com/callback'],
    #       logo_uri: 'https://app.example.com/logo.png'
    #     }
    #   )
    #   metadata.to_h
    #
    # @example Build cancellation metadata
    #   metadata = Safire::Protocols::UdapRegistrationMetadata.new(
    #     {
    #       client_name: 'Example Health App',
    #       contacts: ['mailto:security@example.com'],
    #       scope: 'openid system/Patient.rs'
    #     },
    #     operation: :cancel
    #   )
    #
    # @see https://www.udap.org/udap-dynamic-client-registration-stu1.html
    class UdapRegistrationMetadata
      include URIValidation

      OPERATIONS = %i[register cancel].freeze
      REQUIRED_FIELDS = %w[client_name contacts scope].freeze
      KNOWN_INPUT_FIELDS = %w[
        client_name
        contacts
        grant_types
        scope
        redirect_uris
        logo_uri
      ].freeze
      RESERVED_FIELDS = %w[
        iss
        sub
        aud
        iat
        exp
        jti
        software_statement
        certifications
        udap
        response_types
        token_endpoint_auth_method
      ].freeze
      PRIMARY_GRANT_TYPES = %w[authorization_code client_credentials].freeze
      ALLOWED_GRANT_TYPES = (PRIMARY_GRANT_TYPES + ['refresh_token']).freeze
      AUTHORIZATION_ONLY_FIELDS = %w[redirect_uris logo_uri].freeze
      IMAGE_PATH_PATTERN = /\.(?:png|jpe?g|gif)\z/i
      SCOPE_PATTERN = /\A[!#-\[\]-~]+(?: [!#-\[\]-~]+)*\z/
      JSON_SCALAR_CLASSES = [NilClass, TrueClass, FalseClass, String, Integer].freeze

      private_constant :OPERATIONS, :REQUIRED_FIELDS, :KNOWN_INPUT_FIELDS, :RESERVED_FIELDS,
                       :PRIMARY_GRANT_TYPES, :ALLOWED_GRANT_TYPES, :AUTHORIZATION_ONLY_FIELDS,
                       :IMAGE_PATH_PATTERN, :SCOPE_PATTERN, :JSON_SCALAR_CLASSES

      # @param input [Hash] caller-controlled registration metadata
      # @param operation [:register, :cancel] metadata operation
      # @param allow_insecure_localhost [Boolean] permit HTTP redirect and logo
      #   URIs only on +localhost+ or +127.0.0.1+ for local development; this
      #   produces non-conformant UDAP registration metadata
      # @raise [Safire::Errors::ValidationError] when input violates the STU2
      #   registration metadata contract
      def initialize(input, operation: :register, allow_insecure_localhost: false)
        @operation = validate_operation(operation)
        @allow_insecure_localhost = validate_localhost_policy(allow_insecure_localhost)
        normalized = normalize_input(input)
        validate_reserved_fields!(normalized)
        prepare_operation!(normalized)
        validate_required_fields!(normalized)
        validate_contacts!(normalized)
        validate_scope!(normalized)
        validate_registration_fields!(normalized) if register?
        validate_authorization_fields!(normalized)
        validate_extensions!(normalized)
        generate_protocol_fields!(normalized)
        @metadata = deep_freeze(normalized)
        warn_if_insecure_localhost_used(@metadata)
        freeze
      end

      # Returns a mutable defensive copy of the normalized metadata.
      #
      # @return [Hash<String, Object>]
      def to_h
        deep_copy(@metadata)
      end

      private

      def validate_operation(operation)
        return operation if OPERATIONS.include?(operation)

        fail_validation!(:operation, 'must be register or cancel')
      end

      def validate_localhost_policy(value)
        return value if [true, false].include?(value)

        fail_validation!(:allow_insecure_localhost, 'must be true or false')
      end

      def normalize_input(input)
        fail_validation!(:metadata, 'must be a Hash') unless input.is_a?(Hash)

        input.each_with_object({}) do |(key, value), normalized|
          fail_validation!(:metadata, 'keys must be strings or symbols') unless key.is_a?(String) || key.is_a?(Symbol)

          name = key.to_s
          fail_validation!(name.to_sym, 'must not be specified more than once') if normalized.key?(name)

          normalized[name] = deep_copy(value, attribute: name.to_sym)
        end
      end

      def validate_reserved_fields!(metadata)
        reserved = RESERVED_FIELDS.find { |field| metadata.key?(field) }
        fail_validation!(reserved.to_sym, 'is reserved for Safire') if reserved
      end

      def prepare_operation!(metadata)
        return if register?

        fail_validation!(:grant_types, 'must be omitted for cancellation') if metadata.key?('grant_types')
        AUTHORIZATION_ONLY_FIELDS.each { |field| metadata.delete(field) }
      end

      def validate_required_fields!(metadata)
        required = register? ? REQUIRED_FIELDS + ['grant_types'] : REQUIRED_FIELDS
        missing = required.find { |field| !metadata.key?(field) }
        fail_validation!(missing.to_sym, 'is required') if missing

        validate_non_blank_string!(metadata, 'client_name')
      end

      def validate_contacts!(metadata)
        contacts = metadata['contacts']
        fail_validation!(:contacts, 'must be a non-empty array') unless non_empty_array?(contacts)
        fail_validation!(:contacts, 'must contain only URI strings') unless contacts.all?(String)
        unless contacts.all? { |contact| absolute_uri?(contact) }
          fail_validation!(:contacts, 'must contain only valid absolute URI strings')
        end
        return if contacts.any? { |contact| valid_mailto_contact?(contact) }

        fail_validation!(:contacts, 'must contain at least one valid mailto email address')
      end

      def validate_scope!(metadata)
        validate_non_blank_string!(metadata, 'scope')
        return if SCOPE_PATTERN.match?(metadata['scope'])

        fail_validation!(:scope, 'must be a space-delimited OAuth scope string')
      end

      def validate_registration_fields!(metadata)
        grants = metadata['grant_types']
        fail_validation!(:grant_types, 'must be an array of strings') unless string_array?(grants)

        unsupported = grants - ALLOWED_GRANT_TYPES
        fail_validation!(:grant_types, 'contains an unsupported grant type') if unsupported.any?
        fail_validation!(:grant_types, 'must not contain duplicate values') unless grants.uniq == grants

        primary_grants = grants & PRIMARY_GRANT_TYPES
        fail_validation!(:grant_types, 'must contain exactly one primary grant') unless primary_grants.one?

        return unless grants.include?('refresh_token') && !grants.include?('authorization_code')

        fail_validation!(:grant_types, 'refresh_token requires authorization_code')
      end

      def validate_authorization_fields!(metadata)
        if authorization_code?(metadata)
          validate_redirect_uris!(metadata)
          validate_logo_uri!(metadata)
        elsif register?
          validate_authorization_fields_absent!(metadata)
        end
      end

      def validate_redirect_uris!(metadata)
        fail_validation!(:redirect_uris, 'is required for authorization_code') unless metadata.key?('redirect_uris')

        redirects = metadata['redirect_uris']
        unless string_array?(redirects) && redirects.any?
          fail_validation!(:redirect_uris, 'must be a non-empty array of strings')
        end
        return if redirects.all? { |redirect| allowed_registration_uri?(redirect) }

        fail_validation!(:redirect_uris, 'must contain only absolute HTTPS URIs')
      end

      def validate_logo_uri!(metadata)
        fail_validation!(:logo_uri, 'is required for authorization_code') unless metadata.key?('logo_uri')

        logo_uri = metadata['logo_uri']
        fail_validation!(:logo_uri, 'must be an absolute HTTPS URI') unless allowed_registration_uri?(logo_uri)
        return if image_uri?(logo_uri)

        fail_validation!(:logo_uri, 'must reference a PNG, JPEG, JPG, or GIF resource')
      end

      def validate_authorization_fields_absent!(metadata)
        present = AUTHORIZATION_ONLY_FIELDS.find { |field| metadata.key?(field) }
        fail_validation!(present.to_sym, 'must be absent without authorization_code') if present
      end

      def validate_extensions!(metadata)
        extension_fields = metadata.keys - KNOWN_INPUT_FIELDS
        invalid = extension_fields.find { |field| !json_compatible?(metadata[field]) }
        fail_validation!(invalid.to_sym, 'must contain a JSON-compatible value') if invalid
      end

      def generate_protocol_fields!(metadata)
        metadata['grant_types'] = [] unless register?
        metadata['response_types'] = ['code'] if authorization_code?(metadata)
        metadata['token_endpoint_auth_method'] = 'private_key_jwt'
      end

      def validate_non_blank_string!(metadata, field)
        value = metadata[field]
        return if value.is_a?(String) && value.present?

        fail_validation!(field.to_sym, 'must be a non-blank string')
      end

      def authorization_code?(metadata)
        metadata['grant_types']&.include?('authorization_code')
      end

      def register?
        @operation == :register
      end

      def allowed_registration_uri?(value)
        strict_https_uri?(value) ||
          (@allow_insecure_localhost && localhost_http_uri?(value))
      end

      def warn_if_insecure_localhost_used(metadata)
        return unless @allow_insecure_localhost

        uris = Array(metadata['redirect_uris']) + [metadata['logo_uri']]
        return unless uris.compact.any? { |uri| localhost_http_uri?(uri) }

        Safire.logger.warn(
          '[Safire] allow_insecure_localhost permits development-only HTTP loopback URIs; ' \
          'the resulting UDAP registration metadata is non-conformant and must not be used in production'
        )
      end

      def string_array?(value)
        value.is_a?(Array) && value.all?(String)
      end

      def non_empty_array?(value)
        value.is_a?(Array) && value.any?
      end

      def absolute_uri?(value)
        uri = URI.parse(value)
        return false unless uri.scheme
        return uri.host.present? if %w[http https].include?(uri.scheme)

        true
      rescue URI::Error
        false
      end

      def valid_mailto_contact?(value)
        uri = URI.parse(value)
        return false unless uri.is_a?(URI::MailTo)

        uri.to.split(',').any? { |address| URI::MailTo::EMAIL_REGEXP.match?(address) }
      end

      def image_uri?(value)
        path = Addressable::URI.parse(value).path.to_s
        IMAGE_PATH_PATTERN.match?(path)
      end

      def json_compatible?(value)
        return true if JSON_SCALAR_CLASSES.any? { |type| value.is_a?(type) }
        return value.finite? if value.is_a?(Float)
        return value.all? { |entry| json_compatible?(entry) } if value.is_a?(Array)

        json_object_compatible?(value)
      end

      def json_object_compatible?(value)
        value.is_a?(Hash) &&
          value.keys.all?(String) &&
          value.values.all? { |entry| json_compatible?(entry) }
      end

      def deep_copy(value, ancestors: {}, attribute: :metadata)
        return value.dup if value.is_a?(String)
        return value unless value.is_a?(Hash) || value.is_a?(Array)

        object_id = value.object_id
        fail_validation!(attribute, 'must not contain recursive values') if ancestors.key?(object_id)

        ancestors[object_id] = true
        copy = copy_collection(value, ancestors:, attribute:)
        ancestors.delete(object_id)
        copy
      end

      def copy_collection(value, ancestors:, attribute:)
        return value.map { |entry| deep_copy(entry, ancestors:, attribute:) } if value.is_a?(Array)

        value.to_h do |key, entry|
          [copy_key(key), deep_copy(entry, ancestors:, attribute:)]
        end
      end

      def deep_freeze(value)
        case value
        when Hash
          value.each do |key, entry|
            deep_freeze(key)
            deep_freeze(entry)
          end
        when Array
          value.each { |entry| deep_freeze(entry) }
        end
        value.freeze
      end

      def copy_key(key)
        key.is_a?(String) ? key.dup : key
      end

      def fail_validation!(attribute, reason)
        raise Errors::ValidationError.new(attribute:, reason:)
      end
    end
  end
end
