# frozen_string_literal: true

source 'https://rubygems.org'

# Web framework
gem 'puma', '~> 8.0'
gem 'rackup', '~> 2.1'
gem 'sinatra', '~> 4.0'
gem 'sinatra-contrib', '~> 4.0'

# Safire gem (use local path for development)
gem 'safire', path: '../..'

# Session management
gem 'rack-session', '~> 2.0'

# Environment variable management
gem 'dotenv', '~> 3.0'

group :development do
  gem 'pry-byebug'
  gem 'rerun', '~> 0.14'
end
