# frozen_string_literal: true

source 'https://rubygems.org'

# Web framework
gem 'sinatra', '~> 4.0'
gem 'sinatra-contrib', '~> 4.0'
gem 'rackup', '~> 2.1'
gem 'puma', '~> 6.4'

# Safire gem (use local path for development)
gem 'safire', path: '../..'

# Session management
gem 'rack-session', '~> 2.0'

group :development do
  gem 'rerun', '~> 0.14'
end
