source 'https://rubygems.org'

# Jekyll 4.x for Ruby 4.0+ compatibility
gem 'jekyll', '~> 4.4'

# Use Just-the-Docs theme for clean, searchable documentation
gem 'just-the-docs'

# Jekyll plugins
group :jekyll_plugins do
  gem 'jekyll-feed', '~> 0.17'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
end

# Ruby 4.0+ requires explicit declaration of gems removed from stdlib
gem 'base64'
gem 'bigdecimal'
gem 'csv'
gem 'logger'

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :windows, :jruby do
  gem 'tzinfo', '>= 1', '< 3'
  gem 'tzinfo-data'
end

# Performance-booster for watching directories on Windows
gem 'wdm', '~> 0.1', platforms: %i[windows]

# Lock `http_parser.rb` gem to `v0.8.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem 'http_parser.rb', '~> 0.8.0', platforms: [:jruby]

# For serving locally
gem 'webrick'
