name: CI
permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.3.6']

    steps:
    - uses: actions/checkout@v5

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - name: Run tests
      run: bundle exec rspec

    - name: Run RuboCop
      run: bundle exec rubocop

    - name: Security audit
      run: bundle exec bundler-audit check --update

    - name: Generate documentation
      run: bundle exec yard doc

  # build:
  #   runs-on: ubuntu-latest
  #   needs: test

  #   steps:
  #   - uses: actions/checkout@v4

  #   - name: Set up Ruby
  #     uses: ruby/setup-ruby@v1
  #     with:
  #       ruby-version: '3.3.6'
  #       bundler-cache: true

    # - name: Build gem
    #   run: gem build safire.gemspec

    # - name: Upload gem artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: safire-gem
    #     path: safire-*.gem
