name: Docs

on:
  push:
    branches: [ main ]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.3.6']

    steps:
    - uses: actions/checkout@v5

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # This will run bundle install and cache gems automatically

    - name: Remove /docs/api from .gitignore
      run: sed -i '/\/docs\/api/d' .gitignore
    - name: Generate Ruby yardocs
      run: bin/docs

    - name: Setup Git user
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit api yardocs
      run: git add docs/api && git commit -m "Generate API docs" || echo "No changes to commit"
    - name: Push to gh-pages branch
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        force: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
